"""rag_chunks meta column

Revision ID: 04dc226e612e
Revises: 802b2048c64f
Create Date: 2026-07-18 15:14:02.631705

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04dc226e612e'
down_revision: Union[str, Sequence[str], None] = '802b2048c64f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rag_chunks', sa.Column('meta', sa.JSON(), server_default='{}', nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rag_chunks', 'meta')
    # ### end Alembic commands ###
