"""phase 4-5: dept intro/curriculum/videos, achievements, news ai columns, mock user_id

Revision ID: 802b2048c64f
Revises: fd0a91205e04
Create Date: 2026-07-18 14:48:56.590252

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '802b2048c64f'
down_revision: Union[str, Sequence[str], None] = 'fd0a91205e04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_achievements',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.String(length=100), nullable=False),
    sa.Column('badge_key', sa.String(length=50), nullable=False),
    sa.Column('earned_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_achievements_session_id'), 'user_achievements', ['session_id'], unique=False)
    op.create_table('department_videos',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('department_id', sa.Uuid(), nullable=False),
    sa.Column('title_fa', sa.String(length=300), nullable=False),
    sa.Column('subject', sa.String(length=150), nullable=True),
    sa.Column('semester', sa.Integer(), nullable=True),
    sa.Column('lecturer_name', sa.String(length=200), nullable=True),
    sa.Column('video_url', sa.String(length=500), nullable=False),
    sa.Column('description_fa', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('departments', sa.Column('intro_fa', sa.Text(), nullable=True))
    # server_default is required: departments already has rows, NOT NULL without a default would fail
    op.add_column('departments', sa.Column('curriculum', sa.JSON(), nullable=False, server_default='[]'))
    op.add_column('mock_exam_sessions', sa.Column('user_id', sa.Uuid(), nullable=True))
    op.create_foreign_key('fk_mock_exam_sessions_user_id', 'mock_exam_sessions', 'users', ['user_id'], ['id'])
    op.add_column('news', sa.Column('source_url', sa.String(length=500), nullable=True))
    op.add_column('news', sa.Column('is_ai_draft', sa.Boolean(), nullable=False, server_default='false'))
    op.create_unique_constraint('uq_news_source_url', 'news', ['source_url'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_news_source_url', 'news', type_='unique')
    op.drop_column('news', 'is_ai_draft')
    op.drop_column('news', 'source_url')
    op.drop_constraint('fk_mock_exam_sessions_user_id', 'mock_exam_sessions', type_='foreignkey')
    op.drop_column('mock_exam_sessions', 'user_id')
    op.drop_column('departments', 'curriculum')
    op.drop_column('departments', 'intro_fa')
    op.drop_table('department_videos')
    op.drop_index(op.f('ix_user_achievements_session_id'), table_name='user_achievements')
    op.drop_table('user_achievements')
    # ### end Alembic commands ###
