"""add question_bank and exam improvements

Revision ID: fd0a91205e04
Revises: 
Create Date: 2026-07-17 23:10:33.260813

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fd0a91205e04'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_question_bank_subject'), table_name='question_bank')
    op.drop_table('question_bank')
    op.drop_table('ai_chat_logs')
    op.drop_table('kankor_guides')
    op.drop_table('exam_results')
    op.drop_table('exam_questions')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_table('users')
    op.drop_table('academic_events')
    op.drop_index(op.f('ix_refresh_tokens_token_hash'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_table('kankor_cutoffs')
    op.drop_table('exams')
    op.drop_table('quiz_questions')
    op.drop_table('quiz_options')
    op.drop_index(op.f('ix_admin_users_email'), table_name='admin_users')
    op.drop_table('admin_users')
    op.drop_table('department_trait_profiles')
    op.drop_table('exam_options')
    op.drop_table('rag_chunks')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rag_chunks',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('source_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('source_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('language', sa.VARCHAR(length=5), autoincrement=False, nullable=False),
    sa.Column('embedding', sa.NullType(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['departments.id'], name=op.f('rag_chunks_source_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('rag_chunks_pkey'))
    )
    op.create_table('exam_options',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('question_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('text_fa', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('text_en', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('is_correct', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['exam_questions.id'], name=op.f('exam_options_question_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('exam_options_pkey'))
    )
    op.create_table('department_trait_profiles',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('department_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('trait_weights', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], name=op.f('department_trait_profiles_department_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('department_trait_profiles_pkey')),
    sa.UniqueConstraint('department_id', name=op.f('department_trait_profiles_department_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('admin_users',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('hashed_password', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('full_name', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('role', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('admin_users_pkey'))
    )
    op.create_index(op.f('ix_admin_users_email'), 'admin_users', ['email'], unique=True)
    op.create_table('quiz_options',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('question_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('text_fa', sa.VARCHAR(length=300), autoincrement=False, nullable=False),
    sa.Column('trait_weights', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['quiz_questions.id'], name=op.f('quiz_options_question_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('quiz_options_pkey'))
    )
    op.create_table('quiz_questions',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('question_fa', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('category', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('sort_order', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('quiz_questions_pkey'))
    )
    op.create_table('exams',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('title_fa', sa.VARCHAR(length=300), autoincrement=False, nullable=False),
    sa.Column('title_en', sa.VARCHAR(length=300), autoincrement=False, nullable=True),
    sa.Column('description_fa', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('category', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('year', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('duration_minutes', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('total_questions', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('passing_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('max_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('exams_pkey'))
    )
    op.create_table('kankor_cutoffs',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('department_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('year', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('min_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('capacity', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], name=op.f('kankor_cutoffs_department_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('kankor_cutoffs_pkey'))
    )
    op.create_table('refresh_tokens',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('admin_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('token_hash', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('revoked', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['admin_users.id'], name=op.f('refresh_tokens_admin_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('refresh_tokens_pkey'))
    )
    op.create_index(op.f('ix_refresh_tokens_token_hash'), 'refresh_tokens', ['token_hash'], unique=True)
    op.create_table('academic_events',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('title_fa', sa.VARCHAR(length=300), autoincrement=False, nullable=False),
    sa.Column('description_fa', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('event_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('event_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('remind_days_before', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('academic_events_pkey'))
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('phone', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('full_name', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('hashed_password', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('is_verified', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('users_pkey'))
    )
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=True)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('exam_questions',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('exam_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('question_fa', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('question_en', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('sort_order', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('points', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('subject', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], name=op.f('exam_questions_exam_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('exam_questions_pkey'))
    )
    op.create_table('exam_results',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('exam_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('session_id', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('raw_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('total_points', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('correct_answers', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('wrong_answers', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('empty_answers', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('total_answers', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('subject_scores', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('answers', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('time_taken_seconds', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('started_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('completed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('exam_year', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('compared_to_avg', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], name=op.f('exam_results_exam_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('exam_results_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('exam_results_pkey'))
    )
    op.create_table('kankor_guides',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('title_fa', sa.VARCHAR(length=300), autoincrement=False, nullable=False),
    sa.Column('body_fa', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('category', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('sort_order', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('kankor_guides_pkey'))
    )
    op.create_table('ai_chat_logs',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('session_id', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('user_message', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('ai_response', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('was_cached', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('ai_chat_logs_pkey'))
    )
    op.create_table('question_bank',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('subject', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('difficulty', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('question_fa', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('question_en', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('options', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('explanation_fa', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('source', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('question_bank_pkey'))
    )
    op.create_index(op.f('ix_question_bank_subject'), 'question_bank', ['subject'], unique=False)
    # ### end Alembic commands ###
